site_name: Data - AI - Analytics Reference Architecture
repo_url: https://github.com/ibm-cloud-architecture/refarch-data-ai-analytics
nav:
  - Welcome: index.md
  - Architectures :
    - Runtime application: runtimes/README.md
    - ML & DL pipeline: runtimes/README.md#modeling-architecture
  - Methodology: methodology/README.md
  - Data Topology: 
    - Principles: topology/README.md 
    - Role: topology/README.md
    - Data Structure and scale:  topology/README.md
    - Storage and location: topology/README.md
    - Security:  topology/README.md
    - Temporal life cycle:  topology/README.md
    - Data provenance:  topology/README.md
    - Model representation:  topology/README.md
  - Data Preparation: 
    - Feature selection: preparation/README.md
    - Feature engineering: preparation/README.md
    - Bias picking right training set: preparation/README.md
    - Model selection: preparation/README.md
  - Deployment: 
    - CI & CD: deployment/README.md
    - Physical model execution: deployment/README.md
  - Monitoring: 
    - Feedback analysis:  monitoring/README.md
    - Bias monitoring to ensure equitable:  monitoring/README.md
  

theme: 
  name: material
extra_css: ["extra.css"]
