site_name: Data - AI - Analytics Reference Architecture
repo_url: https://github.com/ibm-cloud-architecture/refarch-data-ai-analytics
nav:
  - Introduction: index.md
  - Architectures :
    - Runtime application: runtimes/README.md
    - ML & DL pipeline: runtimes/#modeling-architecture
  - Methodology: methodology/README.md
  - Data Topology: 
    - Principles: topology/README.md 
    - Role: topology/README.md
    - Data Structure and scale:  topology/README.md
    - Storage and location: topology/README.md
    - Security:  topology/README.md
    - Temporal life cycle:  topology/README.md
    - Data provenance:  topology/README.md
    - Model representation:  topology/README.md
  - Data Preparation: 
    - Feature selection: preparation/README.md
    - Feature engineering: preparation/README.md
    - Bias picking right training set: preparation/README.md
    - Model selection: preparation/README.md
  - Deployment: 
    - CI & CD: deployment/README.md
    - Physical model execution: deployment/README.md
  - Monitoring: 
    - Feedback analysis:  monitoring/README.md
    - Bias monitoring to ensure equitable:  monitoring/README.md
  - Reference Implementation:
    - Customer churn solution: https://ibm-cloud-architecture.github.io/refarch-cognitive-analytics/
  

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences