site_name: Data - AI - Analytics Reference Architecture
repo_url: https://github.com/ibm-cloud-architecture/refarch-data-ai-analytics
nav:
  - Introduction: index.md
  - AI Ladder: data/README.md
  - Data & AI Architectures :
    - Architecture Principles : architecture/README.md
    - Architectural Decision guidelines: architecture/architectural-decisions.md
    - Collect - organize data: architecture/collect-org-data.md
    - Analyze & build model: architecture/build-model.md
    - Infuse in application: architecture/runtime-flow.md
  - Collect and Organize:
    - Data Topology: topology/README.md
    - Data Replication: data/data-replication.md
    - Data Partitioning: data/data-partitioning.md
    - Data Integration: data/data-integration.md
  - Analyze:
    - Data Understanding: preparation/data-understanding.md
    - Data Preparation: preparation/README.md
    - Model selection: preparation/dev-model.md
  - Infuse:
    - CI & CD: deployment/README.md
    - Physical model execution: deployment/README.md
    - Model evaluation: deployment/model-evaluation.md
  - Development practices:
    - Designing intelligent application: architecture/intelligent-app.md
    - Cassandra practices: data/cassandra/readme.md
  - Monitoring:
    - Feedback analysis:  monitoring/README.md
    - Bias monitoring to ensure equitable:  monitoring/README.md
  - Methodology:
    - Integrated iterative approach:  methodology/README.md
    - MLOps: methodology/MLops.md
    - DevOps: methodology/devops.md
    - DataOps: methodology/dataops.md

  - Reference Implementations:
    - Customer churn solution: https://ibm-cloud-architecture.github.io/refarch-ai-data-customer-churn/
    - Reefer container solution: https://ibm-cloud-architecture.github.io/refarch-kc/


theme:
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
